[package]
name = "timelens-storage"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
crc32fast.workspace = true
hex.workspace = true
prost.workspace = true
rusqlite.workspace = true
thiserror.workspace = true
timelens-ipc = { path = "../timelens-ipc" }
windows-sys.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
