[package]
name = "timelens-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
build = "build.rs"

[[bin]]
name = "timelens"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
slint.workspace = true
timelens-ipc = { path = "../timelens-ipc" }
timelens-storage = { path = "../timelens-storage" }

[build-dependencies]
embed-resource.workspace = true
